export const SETPEOPLE = 'SETPEOPLE';
export const FILTERBYNAME = 'FILTERBYNAME';
export const SETSELECTEDNATIONALITY = 'SETSELECTEDNATIONALITY';
export const SETSELECTEDGENDER = 'SETSELECTEDGENDER';
export const CLEARFORM = 'CLEARFORM';
